Repository pingcap/tidb-binlog, pull requests merged in 2019-12, with the labels that each got.

#836 loader: don't refresh table info for some DDL (#613)
  pkg/loader/load.go
  pkg/loader/load_test.go
  reparo/syncer/translate.go
  reparo/syncer/translate_test.go
Labels: status/LGT2, type/cherry-pick

#837 arbiter: discard the repeated kafka message
  arbiter/server.go
  arbiter/server_test.go
Labels: needs-cherry-pick-3.0, status/LGT2, status/can merge, type/bug-fix

#840 *: Add missing error checks and enable errcheck in static-check
  Makefile
  drainer/server.go
  drainer/server_test.go
  drainer/status.go
  pump/node_test.go
  pump/server.go
  pump/server_test.go
  pump/storage/log.go
Labels: status/LGT2, type/enhancement

#848 config txn-total-size-limit in tests
  tests/run.sh
Labels: status/LGT2

#847 drainer: support relay log for syncer
  cmd/drainer/drainer.toml
  drainer/config.go
  drainer/relay/relayer.go
  drainer/relay/relayer_test.go
  drainer/sync/mysql.go
  drainer/sync/mysql_test.go
  drainer/sync/pb.go
  drainer/sync/syncer.go
  drainer/sync/syncer_test.go
  drainer/syncer.go
  pkg/binlogfile/binlogger.go
  pkg/binlogfile/binlogger_test.go
  reparo/file_test.go
Labels: status/LGT2

#846 pump: Add a log for when MVCC is not found for a txn not yet GCed
  pump/storage/storage.go
Labels: status/LGT2

#850 drainer: Fix typo in struct name
  drainer/relay/relayer_test.go
  drainer/sync/mysql_test.go
  drainer/sync/syncer_test.go
  drainer/translator/kafka_test.go
  drainer/translator/mysql_test.go
  drainer/translator/pb_test.go
  drainer/translator/testing.go
Labels: status/LGT1

#852 Bug fix: a DDL p-binlog will be ignored when the c-binlog queried from TiKV
  pump/storage/storage.go
  pump/storage/storage_test.go
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, status/LGT2, status/can merge

#855 Bug fix: a DDL p-binlog will be ignored when the c-binlog queried from TiKV(#852)
  pump/storage/storage.go
  pump/storage/storage_test.go
Labels: status/DNM, status/LGT2

#844 drainer: bugfix, handle "missing column" when a column is getting dro…
  drainer/collector.go
  drainer/schema.go
  drainer/schema_test.go
  drainer/syncer.go
  drainer/translator/flash.go
  drainer/translator/flash_test.go
  drainer/translator/flash_util.go
  drainer/translator/kafka.go
  drainer/translator/mysql.go
  drainer/translator/pb.go
  drainer/translator/translator.go
  drainer/translator/translator_test.go
  go.mod
  go.sum
  pkg/util/util.go
  pump/storage/storage.go
  tests/dailytest/case.go
Labels: status/LGT2, type/cherry-pick

#860 Update parser as latest verison tidb use
  go.mod
  go.sum
Labels: status/LGT2

#856 tests: Make sure the INSERT is executed before we starts droppling cols
  tests/dailytest/case.go
Labels: status/LGT2

#859 Update parser as the latest version tidb use
  go.mod
  go.sum
Labels: status/LGT2

#858 Add unique key info in slave proto
  drainer/translator/kafka.go
  drainer/translator/kafka_test.go
  go.mod
  go.sum
Labels: needs-cherry-pick-3.0, status/LGT2, status/can merge

#861 Use format tidb-tools
  go.mod
  go.sum
Labels: status/LGT2

#849 drainer: support reading from relay log
  cmd/drainer/drainer.toml
  drainer/config.go
  drainer/relay/reader.go
  drainer/relay/reader_test.go
  drainer/relay/relayer_test.go
  pkg/binlogfile/binlogger.go
Labels: status/LGT2, status/can merge
