Repository pingcap/tidb-binlog, pull requests merged in 2019-10, with the labels that each got.

#755 *: Output user friendly msg when go mod tidy is needed
  tools/check/check-tidy.sh
Labels: status/LGT2

#756 upgrade grpc to 1.23
  drainer/server.go
  go.mod
  go.sum
  pump/node.go
  pump/server.go
Labels: status/LGT2

#726 pump: Clean up obsolete value logs concurrently
  pump/storage/storage.go
  pump/storage/vlog.go
  pump/storage/vlog_test.go
Labels: status/LGT2, status/PTAL

#727 Refine pump server to make it not to notify drainer when recovering from status 'paused'
  drainer/config.go
  pump/node.go
  pump/server.go
  pump/server_test.go
  tests/status/run.sh
Labels: status/LGT1

#760 drainer: refine log when meeting duplicate binlog
  drainer/merge.go
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, priority/unimportant, status/LGT2, type/enhancement

#761 storage.go: Make query tikv for ddl too (#757)
  pump/storage/storage.go
Labels: status/LGT1, type/cherry-pick

#763 merge.go: Distinct disorder and duplicate cast in log
  drainer/merge.go
Labels: status/LGT2

#765 pump/server.go: Add warn log for slow response
  pump/server.go
Labels: needs-cherry-pick-2.1, status/LGT1, status/PTAL

#766 pump/server.go: Add warn log for slow response (#765)
  pump/server.go
Labels: status/PTAL, type/cherry-pick

#762 Commit Go 1.13 changes to go.mod
  go.mod
  tools/check/go.mod
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, status/LGT2

#769 drainer: Bugfix, should handle ActionModifySchemaCharsetAndCollate correctly
  drainer/schema.go
  drainer/schema_test.go
  tests/dailytest/case.go
Labels: bug, needs-cherry-pick-2.1, needs-cherry-pick-3.0, status/LGT2

#770 drainer: Bugfix, should handle ActionModifySchemaCharsetAndCollate correctly
  drainer/schema.go
  drainer/schema_test.go
  tests/dailytest/case.go
Labels: status/LGT2, type/bug-fix, type/cherry-pick

#767 Commit Go 1.13 changes to go.mod (#762)
  go.mod
  tools/check/go.mod
Labels: status/LGT1, type/cherry-pick

#773 pump/storge: Measure time taken to write to disk, to rotate and fsync
  pump/storage/log.go
  pump/storage/vlog.go
Labels: needs-cherry-pick-2.1, status/LGT2, status/PTAL

#776 *: revert #756, use gRPC 1.17
  drainer/server.go
  go.mod
  go.sum
  pump/node.go
  pump/server.go
Labels: status/LGT2

#774 binlogctl: Only show offline nodes when explicitly told so
  binlogctl/config.go
  binlogctl/nodes.go
  binlogctl/nodes_test.go
  cmd/binlogctl/main.go
  tests/_utils/check_status
Labels: need-update-docs, status/LGT2, status/PTAL

#778 kafka.go: Refine log
  Makefile
  drainer/sync/kafka.go
  drainer/translator/flash.go
  go.mod
  go.sum
  pkg/util/log.go
  pump/storage/helper.go
  pump/storage/storage.go
  reparo/config.go
  tools/check/go.mod
  tools/check/go.sum
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/LGT2, status/can merge

#780 kafka.go: Refine log (#778)
  Makefile
  drainer/sync/kafka.go
  drainer/translator/flash.go
  go.sum
  pkg/util/log.go
  reparo/config.go
  tools/check/go.mod
  tools/check/go.sum
Labels: status/LGT2, status/can merge, type/cherry-pick

#782 kafka.go: Refine log (#778)
  Makefile
  drainer/executor/kafka.go
  drainer/translator/flash.go
  reparo/config.go
  tools/check/go.mod
  tools/check/go.sum
Labels: status/LGT2, status/can merge, type/cherry-pick

#785 drainer/*: use enable-** in 4.0
  cmd/drainer/drainer.toml
  drainer/config.go
  drainer/config_test.go
  tests/binlog/drainer.toml
  tests/filter/drainer.toml
  tests/gencol/drainer.toml
  tests/kafka/drainer.toml
  tests/reparo/drainer.toml
  tests/restart/drainer.toml
  tests/status/drainer.toml
Labels: status/LGT2, status/can merge
