Repository pingcap/tidb-binlog, pull requests merged in 2019-09, with the labels that each got.

#742 reparo/:Add worker-count, txn-batch config
  cmd/reparo/reparo.toml
  reparo/config.go
  reparo/reparo.go
  reparo/syncer/mysql.go
  reparo/syncer/mysql_test.go
  reparo/syncer/syncer.go
  reparo/syncer/syncer_test.go
Labels: needs-cherry-pick-2.1, status/LGT2

#739 fix pump storage quit bug
  pump/server.go
Labels: status/LGT1

#745 fix pump pull pop bug while closing pump
  pump/server.go
  pump/server_test.go
Labels: status/LGT2, type/cherry-pick

#744 tests: Rewrite updatePKUK to avoid outputing a lot of messages about generating PKs
  tests/dailytest/case.go
Labels: status/LGT2

#735 drainer/: Change unreasonable buff size and reduce memory usage
  drainer/checkpoint/mysql.go
  drainer/config.go
  drainer/merge.go
  drainer/metrics.go
  drainer/pump.go
  drainer/syncer.go
  tests/status/run.sh
Labels: status/LGT2, type/enhancement

#740 Refine BIT test & Fix arbiter bug(#667 & #714)
  arbiter/server.go
  pkg/loader/translate.go
  tests/dailytest/case.go
  tests/kafka/kafka.go
  tests/update_bit1/drainer.toml
  tests/update_bit1/run.sh
Labels: status/LGT2, type/cherry-pick

#746 reparo/:Add worker-count, txn-batch config (#742)
  cmd/reparo/reparo.toml
  reparo/config.go
  reparo/reparo.go
  reparo/syncer/mysql.go
  reparo/syncer/mysql_test.go
  reparo/syncer/syncer.go
  reparo/syncer/syncer_test.go
Labels: status/LGT2, type/cherry-pick

#747 optimize drainer syncer quit
  drainer/syncer.go
Labels: status/LGT2

#750 *: add binlogctl
  Makefile
  binlogctl/config.go
  binlogctl/config_test.go
  binlogctl/meta.go
  binlogctl/meta_test.go
  binlogctl/nodes.go
  binlogctl/nodes_test.go
  cmd/binlogctl/README.md
  cmd/binlogctl/main.go
  pkg/node/node.go
  pkg/util/ts.go
Labels: priority/normal, status/PTAL, type/cherry-pick

#749 pkg/loader: fix loader run while quitting
  drainer/sync/mysql.go
  drainer/sync/mysql_test.go
  drainer/sync/syncer_test.go
Labels: status/LGT2

#752 fix pump server_test
  pump/server_test.go
Labels: status/LGT1

#754 go.mod: Update parser version as newest tidb 3.0 uses
  go.mod
  go.sum
Labels: status/PTAL

#737 drainer/: Reduce memory usage (#735)
  drainer/config.go
  drainer/merge.go
  drainer/metrics.go
  drainer/pump.go
  drainer/pump_test.go
  drainer/sync/syncer.go
  drainer/sync/syncer_test.go
  pkg/loader/load.go
  pkg/loader/load_test.go
  tests/kafka/kafka.go
  tests/status/run.sh
Labels: status/LGT2, status/PTAL, type/cherry-pick

#757 storage.go: Make query tikv for ddl too
  pump/storage/storage.go
Labels: needs-cherry-pick-2.1, status/LGT2

#758 pump.Storage: fix possible panic if start ts is greater than max commit ts when pull binlog
  pump/storage/sorter.go
  pump/storage/storage.go
  pump/storage/vlog.go
Labels: needs-cherry-pick-2.1, priority/normal, status/LGT1, status/PTAL, type/bug-fix

#759 pump.Storage: fix possible panic if start ts is greater than max commit ts when pull binlog
  pump/storage/storage.go
Labels: priority/normal, status/LGT2, type/cherry-pick
