Repository pingcap/tidb-binlog, pull requests merged in 2019-06, with the labels that each got.

#628 limit gc speed (#620)
  go.mod
  go.sum
  pump/storage/storage.go
Labels: status/LGT1, type/cherry-pick

#631 pump: Add config to set cap buf of kv_chan
  pump/server.go
  pump/storage/storage.go
  pump/storage/vlog.go
Labels: status/LGT1

#629 *: empty host should not be considered valid, fix #627
  pkg/util/util.go
  pkg/util/util_test.go
  pump/config.go
  pump/config_test.go
  tests/_utils/run_pump
Labels: status/LGT2, type/enhancement

#635 tests: Reduce binlog_big test txn data
  tests/dailytest/case.go
Labels: status/LGT2, status/PTAL, type/test

#630 *: add some unit tests and remove unused code
  pkg/util/kafka.go
  pkg/util/util_test.go
  reparo/syncer/mysql.go
  reparo/syncer/mysql_test.go
  reparo/syncer/translate_test.go
  reparo/syncer/util_test.go
Labels: priority/unimportant, status/LGT1, type/test

#636 pkg/binlogfile: Fix test
  pkg/binlogfile/binlogger.go
  pkg/binlogfile/binlogger_test.go
Labels: status/PTAL, type/test

#637 pump: Allow 127.0.0.1 for advertise-addr
  pump/config.go
  pump/config_test.go
Labels: status/LGT2

#613 loader/: don't refresh table info for some DDL
  pkg/loader/load.go
  pkg/loader/load_test.go
  pkg/loader/util.go
  pkg/loader/util_test.go
  reparo/syncer/translate.go
  reparo/syncer/translate_test.go
Labels: status/LGT2, type/enhancement

#634 Add config advertise-addr for drainer
  cmd/drainer/drainer.toml
  drainer/config.go
  drainer/config_test.go
  drainer/server.go
Labels: status/LGT2

#632 pump/: Accelerat transaction status queries throught GetMvccByEncodeKey
  go.mod
  pump/server.go
  pump/storage/helper.go
  pump/storage/storage.go
Labels: p0, priority/important, status/LGT2

#638 drainer: Log version info before other logs, fix #242
  cmd/drainer/main.go
Labels: status/LGT1, type/enhancement

#640 vlog.go: Fix wrongly maintain the offset of file in memory
  pump/storage/vlog.go
  pump/storage/vlog_test.go
Labels: priority/important, status/LGT2, type/bug-fix

#642 vlog.go: Fix wrongly maintain the offset of file in memory (#640)
  pump/storage/vlog.go
  pump/storage/vlog_test.go
Labels: status/LGT2, type/bug-fix, type/cherry-pick

#639 pump: Fix #560, retry connection and request when notifying drainers
  pkg/util/util.go
  pkg/util/util_test.go
  pump/node.go
Labels: status/LGT1, type/enhancement

#643 binlogctl: return error when cmd not supported
  cmd/binlogctl/main.go
Labels: priority/unimportant, status/LGT2

#644 Cherry pick advertise-addr related changes from master
  cmd/drainer/drainer.toml
  drainer/config.go
  drainer/config_test.go
  drainer/server.go
  pkg/util/util.go
  pump/config.go
  pump/config_test.go
Labels: status/LGT1, type/cherry-pick

#652 reparo: add safe mode config
  reparo/config.go
  reparo/reparo.go
  reparo/syncer/mysql.go
  reparo/syncer/mysql_test.go
  reparo/syncer/syncer.go
  reparo/syncer/syncer_test.go
Labels: priority/normal, status/LGT2, type/feature

#645 Revert "drainer: Log version info before other logs, fix #242"
  cmd/drainer/main.go
Labels: status/LGT2

#651 pump/storage: Avoid big inputs that slow down the unit test
  pump/storage/storage_test.go
  pump/storage/vlog_test.go
Labels: status/LGT2, type/enhancement

#648 pump/: Fix get L0 files num and trigger vlog.gcTS step by step
  go.mod
  go.sum
  pump/server.go
  pump/storage/storage.go
  pump/storage/vlog.go
Labels: priority/important, status/LGT2, status/PTAL

#647 pump: Add support to stop write at a limit avaliable space
  cmd/pump/pump.toml
  go.mod
  pump/server.go
  pump/server_test.go
  pump/storage/errors.go
  pump/storage/storage.go
  pump/storage/util.go
  pump/storage/util_test.go
  pump/storage/vlog.go
Labels: priority/important, status/LGT2

#646 refine gc strategy of pump
  pump/config.go
  pump/metrics.go
  pump/server.go
  pump/server_test.go
  pump/storage/storage.go
Labels: priority/important, status/LGT1

#649 pump/storage: Refactor, encapsulate writing and offset updating in logFile
  pump/storage/log.go
  pump/storage/log_test.go
  pump/storage/vlog.go
Labels: priority/important, status/LGT2

#654 pump: record levelDB iterator error during gc
  pump/storage/storage.go
Labels: priority/unimportant, status/LGT2, type/enhancement
