Repository pingcap/tidb-binlog, pull requests merged in 2019-05, with the labels that each got.

#571 drainer: Refactor and add unit tests
  drainer/collector.go
  drainer/collector_test.go
  drainer/pump.go
  drainer/schema_test.go
Labels: status/LGT1, type/test

#585 pkg/loader: Refactor and add tests for translate functions
  pkg/loader/translate.go
  pkg/loader/translate_test.go
Labels: status/LGT2

#590 *: Upgrade to pingcap/errors@v1.11.1
  go.mod
  go.sum
  pkg/loader/executor.go
Labels: status/LGT2

#586 pkg/loader: Refactor and add tests for executor
  pkg/loader/executor.go
  pkg/loader/executor_test.go
  pkg/loader/model.go
  pkg/loader/util.go
Labels: status/LGT2, type/test

#592 pkg/loader: Add tests for load
  pkg/loader/load.go
  pkg/loader/load_test.go
Labels: status/LGT2, type/test

#593 drainer: Ignore empty string when getting compressor config
  drainer/pump.go
  drainer/pump_test.go
Labels: status/LGT2

#596 *: Create a reusable metricClient in util
  arbiter/metrics.go
  arbiter/metrics_test.go
  arbiter/server.go
  arbiter/server_test.go
  drainer/metrics.go
  drainer/server.go
  pkg/util/p8s.go
  pkg/util/p8s_test.go
  pump/metrics.go
  pump/server.go
Labels: status/LGT2

#595 Turn fatal error listening on 127.0.0.1/localhost into a warning (was #561)
  drainer/config.go
Labels: status/LGT1

#599 [2.1] Make release2.1 run linters and pass ci `check`
  .gitignore
  Makefile
  cmd/drainer/main.go
  cmd/pump/main.go
  drainer/executor/bench_kafka_test.go
  drainer/pump.go
  drainer/schema.go
  drainer/schema_test.go
  drainer/syncer_test.go
  go.sum
  pkg/binlogfile/binlogger.go
  pump/server.go
  pump/storage/vlog.go
  reparo/ddl_test.go
  reparo/reparo_test.go
  reparo/syncer/translate_test.go
  tests/dailytest/case.go
  tests/dailytest/data.go
  tests/dailytest/db.go
  tests/dailytest/ddl.go
  tests/dailytest/job.go
  tests/dailytest/parser.go
  tests/dailytest/rand.go
  tests/util/db.go
  tools/check/check-tidy.sh
  tools/check/go.mod
  tools/check/go.sum
  tools/check/revive.toml
Labels: priority/important, status/LGT1, type/cherry-pick

#598 drainer: Ignore empty string when getting compressor config (#593)
  drainer/pump.go
  drainer/pump_test.go
Labels: status/LGT2, type/cherry-pick

#600 *: Fix some missing error checks as reported by golangci-lint
  .gitignore
  arbiter/config.go
  arbiter/config_test.go
  binlogctl/nodes_test.go
  cmd/arbiter/main.go
  cmd/drainer/main.go
  cmd/pump/main.go
  cmd/reparo/main.go
  drainer/collector.go
  drainer/config.go
  drainer/server.go
  drainer/sync/flash.go
  pkg/binlogfile/binlogger_test.go
  pkg/flags/flag_test.go
  pkg/loader/bench_test.go
  pkg/loader/load_test.go
  pkg/security/security_test.go
  pkg/util/log_test.go
  pkg/util/signal_test.go
  pump/config.go
  pump/server.go
  pump/storage/log_test.go
  pump/storage/storage.go
  pump/storage/vlog_test.go
  reparo/config.go
  reparo/file_test.go
  tests/binlog/binlog.go
  tests/flash/flash.go
Labels: status/LGT2, type/enhancement

#601 drainer: Add unit tests
  drainer/collector.go
  drainer/collector_test.go
  drainer/config_test.go
  drainer/server.go
  drainer/server_test.go
  drainer/util.go
  drainer/util_test.go
Labels: status/LGT2, status/PTAL, type/test

#608 go.mod: Update parser dep
  go.mod
  go.sum
Labels: status/LGT2, status/PTAL

#607 pump/*: Refine some log in storage/
  pump/server.go
  pump/storage/log.go
  pump/storage/storage.go
  pump/storage/vlog.go
Labels: priority/important, status/LGT2, status/PTAL

#610 *: Fix typos
  drainer/collector.go
  drainer/config.go
  drainer/sync/kafka.go
  pkg/node/registry.go
  pkg/util/log.go
  pump/storage/log.go
  pump/storage/storage.go
  reparo/config.go
Labels: status/LGT2

#604 binlogctl: add unit test
  binlogctl/meta.go
  binlogctl/meta_test.go
  binlogctl/nodes.go
  binlogctl/nodes_test.go
Labels: status/LGT1, status/PTAL, type/test

#609 CHANGELOG.md: Add 2.1.10
  CHANGELOG.md
Labels: status/LGT1

#603 pump,pkg/util: Refactor and add more unit tests
  pkg/util/util.go
  pkg/util/util_test.go
  pump/node.go
  pump/node_test.go
  pump/server.go
  pump/server_test.go
Labels: status/LGT2, status/PTAL, type/test

#611 load.go: set max idle conns as worker count
  pkg/loader/load.go
Labels: priority/important, status/LGT2, type/enhancement

#616 doc: Add more badges on README
  README.md
Labels: status/LGT2

#617 pump: getSafeGCTSOForDrainers should be usable after Close
  pump/server.go
Labels: status/LGT2, type/bug-fix

#594 drainer: Add a metric to track the delay of the downstream
  drainer/metrics.go
  drainer/syncer.go
Labels: status/LGT2

#618 *: Fix golint complaints
  drainer/syncer.go
  drainer/translator/flash_util.go
Labels: status/LGT2

#619 pump/*: Refine some log in storage/ (#607)
  pump/storage/log.go
  pump/storage/storage.go
  pump/storage/vlog.go
Labels: status/LGT1, status/PTAL, type/enhancement

#614 tests: Support selecting multiple cases to run
  tests/run.sh
Labels: status/LGT2, type/test

#621 reparo: refine integration test
  pkg/loader/load.go
  pkg/loader/load_test.go
  reparo/syncer/translate.go
  reparo/syncer/translate_test.go
  tests/reparo/binlog.go
  tests/reparo/config.toml
  tests/reparo/reparo.toml
  tests/reparo/run.sh
  tests/reparo/sync_diff_inspector.toml
Labels: priority/important, status/LGT1, type/bug-fix, type/test

#623 reparo: refine integration test
  go.mod
  go.sum
  pkg/loader/load.go
  reparo/syncer/translate.go
  reparo/syncer/translate_test.go
  tests/reparo/binlog.go
  tests/reparo/config.toml
  tests/reparo/reparo.toml
  tests/reparo/run.sh
  tests/reparo/sync_diff_inspector.toml
Labels: status/LGT2, type/cherry-pick

#622 drainer: Log close error and long waits
  drainer/syncer.go
Labels: status/LGT2

#625 tests: fix the value range when checking exec txn histogram
  pkg/sql/sql_test.go
Labels: priority/unimportant, status/LGT2, type/test

#624 pump/storage: Random cleanups
  pump/storage/storage.go
  pump/storage/vlog.go
Labels: status/LGT2

#626 pump: Refactor storage to make it easier to extend
  pump/storage/storage.go
  pump/storage/storage_test.go
  pump/storage/vlog.go
Labels: status/LGT2

#615 *: Simplify checkpoint
  drainer/checkpoint/checkpoint.go
  drainer/checkpoint/flash.go
  drainer/checkpoint/flash_test.go
  drainer/checkpoint/kafka_test.go
  drainer/checkpoint/mysql.go
  drainer/checkpoint/mysql_test.go
  drainer/checkpoint/pb.go
  drainer/checkpoint/pb_test.go
  drainer/syncer.go
  pkg/flash/meta_checkpoint.go
  pkg/flash/meta_checkpoint_test.go
  tools/check/check-tidy.sh
Labels: status/LGT1, type/enhancement
