Repository pingcap/tidb-binlog, pull requests merged in 2019-11, with the labels that each got.

#777 binlogctl: Hide offline pumps/drainers by default
  binlogctl/config.go
  binlogctl/nodes.go
  binlogctl/nodes_test.go
  cmd/binlogctl/main.go
  tests/_utils/check_status
Labels: status/LGT2, type/cherry-pick

#787 drainer/*: get latest timestamp from pd when initial-commit-ts is -1
  drainer/config.go
  drainer/server.go
  tests/dailytest/case.go
  tests/kafka/run.sh
  tests/reparo/run.sh
  tests/restart/run.sh
  tests/status/run.sh
Labels: need-update-docs, needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/LGT2, status/can merge

#786 *: Decouple Checkpoint type from dest-type
  cmd/drainer/drainer.toml
  drainer/checkpoint/checkpoint.go
  drainer/checkpoint/file.go
  drainer/checkpoint/file_test.go
  drainer/checkpoint/kafka.go
  drainer/checkpoint/kafka_test.go
  drainer/checkpoint/mysql.go
  drainer/checkpoint/mysql_test.go
  drainer/checkpoint/util.go
  drainer/server.go
  drainer/server_test.go
  drainer/sync/util.go
  drainer/syncer_test.go
  drainer/util.go
  pump/storage/storage_test.go
  tests/kafka/drainer.toml
Labels: need-update-docs, needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/LGT1

#792 commit the dashboard and alter config about arbiter
  arbiter/README_CN.md
  arbiter/arbiter.json
  arbiter/arbiter.rules.yml
Labels: already-cherry-pick-3.0, already-cherry-pick-3.1, status/LGT2

#799 Fix panic of empty value in filter config
  drainer/config.go
  drainer/config_test.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/LGT2

#793 pump/storge: Measure time taken to write to disk, to rotate and fsync
  pump/storage/log.go
  pump/storage/vlog.go
Labels: status/LGT1, type/cherry-pick

#794 pump/storge: Measure time taken to write to disk, to rotate and fsync
  pump/storage/log.go
  pump/storage/vlog.go
Labels: status/LGT1, type/cherry-pick

#804 upgrade grpc to 1.23 (#756)
  drainer/server.go
  go.mod
  go.sum
  pump/node.go
  pump/server.go
Labels: priority/important, status/LGT2, type/cherry-pick

#802 Fix panic of empty value in filter config (#799)
  drainer/config.go
  drainer/config_test.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: status/LGT2, type/cherry-pick

#806 fix deadlock while drainer.Syncer panic
  drainer/syncer.go
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/LGT2, status/can merge, type/bug-fix

#809 loader: add a log when table not found
  pkg/loader/util.go
  pkg/loader/util_test.go
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/LGT2, status/can merge

#814 update deps refine some log
  Makefile
  arbiter/config.go
  arbiter/server.go
  binlogctl/nodes_test.go
  cmd/arbiter/arbiter.toml
  cmd/arbiter/main.go
  drainer/config_test.go
  drainer/util.go
  drainer/util_test.go
  go.mod
  go.sum
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/node/registry_test.go
  pump/server_test.go
  tests/util/db.go
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/LGT2

#816 update deps refine some log (#814)
  Makefile
  arbiter/config.go
  arbiter/server.go
  binlogctl/nodes_test.go
  cmd/arbiter/arbiter.toml
  cmd/arbiter/main.go
  drainer/config_test.go
  drainer/util.go
  drainer/util_test.go
  go.mod
  go.sum
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/node/registry_test.go
  pump/server_test.go
  tests/util/db.go
Labels: status/LGT1, type/cherry-pick

#813 add timeout for gs.GracefulStop
  pkg/util/util.go
  pkg/util/util_test.go
  pump/server.go
Labels: status/LGT2

#818 pkg/loader: Fix unstable unit tests
  pkg/loader/load_test.go
Labels: status/LGT2, type/test

#803 drainer: bugfix, handle "missing column" when a column is getting dropped
  drainer/collector.go
  drainer/schema.go
  drainer/schema_test.go
  drainer/syncer.go
  drainer/translator/flash.go
  drainer/translator/flash_test.go
  drainer/translator/kafka.go
  drainer/translator/mysql.go
  drainer/translator/pb.go
  drainer/translator/table_info.go
  drainer/translator/testing.go
  drainer/translator/translator.go
  go.mod
  go.sum
  pkg/util/util.go
  tests/dailytest/case.go
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, status/LGT2, type/bug-fix

#821 drainer: bugfix, handle "missing column" when a column is getting dropped
  drainer/collector.go
  drainer/schema.go
  drainer/schema_test.go
  drainer/server.go
  drainer/syncer.go
  drainer/translator/flash.go
  drainer/translator/flash_test.go
  drainer/translator/kafka.go
  drainer/translator/mysql.go
  drainer/translator/pb.go
  drainer/translator/table_info.go
  drainer/translator/testing.go
  drainer/translator/translator.go
  go.mod
  go.sum
  pkg/util/util.go
  pump/node.go
  pump/server.go
  tests/dailytest/case.go
Labels: status/LGT2, type/cherry-pick

#812 drainer: remove deprecated syncer flash
  cmd/drainer/drainer.toml
  drainer/checkpoint/checkpoint.go
  drainer/checkpoint/flash.go
  drainer/checkpoint/flash_test.go
  drainer/sync/flash.go
  drainer/sync/flash_test.go
  drainer/sync/syncer_test.go
  drainer/sync/util.go
  drainer/syncer.go
  drainer/translator/flash.go
  drainer/translator/flash_util.go
  drainer/util.go
  go.mod
  go.sum
  tests/binlog/drainer.toml
  tests/filter/drainer.toml
  tests/flash/config.toml
  tests/flash/flash.go
  tests/kafka/drainer.toml
  tests/reparo/drainer.toml
  tests/restart/drainer.toml
  tests/status/drainer.toml
Labels: need-update-ansible, need-update-docs, status/LGT2

#825 cherry pick #813, refine grpc graceful stop
  pkg/util/util.go
  pump/server.go
Labels: status/LGT1

#827 drainer: bugfix, handle "missing column" when a column is getting dropped
  drainer/collector.go
  drainer/schema.go
  drainer/schema_test.go
  drainer/syncer.go
  drainer/translator/flash.go
  drainer/translator/flash_test.go
  drainer/translator/kafka.go
  drainer/translator/mysql.go
  drainer/translator/pb.go
  drainer/translator/table_info.go
  drainer/translator/testing.go
  drainer/translator/translator.go
  go.mod
  go.sum
  pkg/util/util.go
  tests/dailytest/case.go
Labels: status/LGT1, type/cherry-pick

#823 avoid oom when there is lag and binlog size is big
  arbiter/config.go
  arbiter/server.go
  drainer/pump.go
  drainer/sync/kafka.go
  go.mod
  go.sum
Labels: status/LGT1

#833 *: Fix #828, GOPATH is no longer required to build binlog projects
  Makefile
Labels: status/LGT1

#805 doc: add http api doc
  docs/binlog_http_api.md
Labels: status/PTAL

#830 pump/storge: Measure time taken to write to disk, to rotate and fsync
  pump/storage/vlog.go
Labels: status/LGT2, type/cherry-pick

#831 binlogctl: Only show offline nodes when explicitly told so (#774)
  binlogctl/config.go
  binlogctl/nodes.go
  binlogctl/nodes_test.go
  cmd/binlogctl/main.go
  tests/_utils/check_status
Labels: status/PTAL, type/cherry-pick

#834 avoid oom when there is lag and binlog size is big (#823)
  arbiter/config.go
  arbiter/server.go
  drainer/pump.go
  drainer/sync/kafka.go
  go.mod
  go.sum
Labels: status/LGT2, type/cherry-pick

#826 *: Check errors
  drainer/collector.go
  drainer/server.go
  pkg/loader/bench_test.go
  pkg/loader/executor.go
  pkg/loader/load.go
  pump/server.go
  pump/status.go
  pump/storage/chaser_test.go
  pump/storage/storage.go
Labels: status/PTAL, type/enhancement

#829 Scripts : Add ci script
  scripts/groovy/binlog_ghpr_build.groovy
  scripts/groovy/binlog_ghpr_check.groovy
  scripts/groovy/binlog_ghpr_integration.groovy
  scripts/groovy/binlog_ghpr_unit_test.groovy
Labels: status/LGT2
