Repository pingcap/tidb-binlog, pull requests merged in 2019-08, with the labels that each got.

#691 loader: stop retry execute sqls when closed
  pkg/loader/executor.go
  pkg/loader/executor_test.go
  pkg/loader/load.go
  pkg/loader/load_test.go
Labels: priority/normal, status/LGT2, type/enhancement

#696 Add several UTs to improve drainer's coverage
  drainer/collector.go
  drainer/collector_test.go
  drainer/config.go
  drainer/config_test.go
  drainer/merge.go
  drainer/merge_test.go
  drainer/pump_test.go
  drainer/schema_test.go
Labels: status/LGT2, status/PTAL, type/test

#697 drainer/: Add ignore-txn-commit-ts to skip some txn (#685)
  cmd/drainer/drainer.toml
  drainer/config.go
  drainer/syncer.go
  drainer/syncer_test.go
Labels: status/LGT2, type/cherry-pick

#700 add issue templates for bugs, features, questions
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/general-question.md
Labels: status/PTAL

#702 Add metric for batch write kv
  pump/storage/storage.go
Labels: status/LGT2

#701 pump/: Fix block at wait for MaxCommitTS when offline
  pump/server.go
  pump/server_test.go
  pump/storage/sorter.go
  pump/storage/sorter_test.go
  pump/storage/storage.go
Labels: needs-cherry-pick-2.1, priority/important, status/LGT2, type/bug-fix

#703 pump/: Fix block at wait for MaxCommitTS when offline (#701)
  pump/server.go
  pump/storage/sorter.go
  pump/storage/sorter_test.go
  pump/storage/storage.go
Labels: status/LGT2, type/cherry-pick

#704 Use mustExec to simplify SQL execution in test cases
  tests/dailytest/case.go
Labels: status/PTAL

#705 update parser in go.mode & go.sum to tidb release 2.1
  go.mod
  go.sum
Labels: status/LGT2

#709 Pump: Fix pump server start process
  pump/node.go
  pump/server.go
Labels: status/LGT2

#708 Return error when loading some undefined configs from local
  arbiter/config.go
  arbiter/config_test.go
  drainer/config.go
  drainer/config_test.go
  pkg/util/util.go
  pump/config.go
  pump/config_test.go
  reparo/config.go
  reparo/config_test.go
Labels: status/LGT2, type/cherry-pick

#706 add node-id cmd to specify drainer's node-id
  cmd/drainer/README.md
  cmd/pump/README.md
  drainer/config.go
  drainer/server.go
  pump/config.go
Labels: status/LGT2, type/cherry-pick

#710 drainer: Remove unused waitGroup
  drainer/syncer.go
Labels: status/PTAL

#711 refine case name and add split region test
  tests/dailytest/case.go
Labels: status/LGT1, status/PTAL

#716 fix pump init order, register the node after listen ports (#709)
  pump/node.go
  pump/server.go
Labels: status/LGT1, type/cherry-pick

#718 Avoid repeated called of NewIterator which might be slow
  pump/storage/metrics.go
  pump/storage/storage.go
Labels: needs-cherry-pick-2.1, status/LGT2

#714 fix bug when some error occurs in loader arbiter's syncBinlog may block
  arbiter/server.go
  arbiter/server_test.go
Labels: status/LGT2

#725 pkg: add resource close in test case
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/zk/zk_test.go
Labels: priority/unimportant, status/LGT2, type/test

#722 fix iter may not be Released in some cases
  pump/storage/storage.go
Labels: needs-cherry-pick-2.1, status/LGT2

#720 Avoid repeated calls of NewIterator which might be slow (#718 & #722)
  pump/storage/metrics.go
  pump/storage/storage.go
Labels: status/LGT2, type/cherry-pick

#723 add drainer notify test for pump node
  pump/node_test.go
Labels: status/LGT1

#721 Change default cache count from 65536 to 512
  drainer/config.go
Labels: needs-cherry-pick-2.1, status/LGT1, status/PTAL

#719 Add some UTs for pump server
  pump/server.go
  pump/server_test.go
Labels: status/LGT2

#729 Avoid risk of ignoring failed to read checkpoint
  drainer/checkpoint/mysql.go
Labels: status/LGT1, status/PTAL, type/bug-fix, type/enhancement

#728 test: add test for metadata gc
  pump/storage/storage.go
  pump/storage/storage_test.go
Labels: needs-cherry-pick-2.1, status/LGT2

#733 test: add test for metadata gc (#728)
  pump/storage/storage.go
  pump/storage/storage_test.go
Labels: status/LGT2, type/cherry-pick
