Repository pingcap/tidb-binlog, pull requests merged in 2019-07, with the labels that each got.

#653 pump/storage: More lightweight unit tests
  pump/storage/sorter.go
  pump/storage/sorter_test.go
  pump/storage/storage_test.go
  pump/storage/vlog_test.go
Labels: status/LGT1

#650 pump/storage: Only hold the lock when collecting logFiles to scan
  pump/storage/vlog.go
Labels: priority/important, status/LGT2

#655 drainer: fix failure to update BIT columns with downstream TiDB
  drainer/translator/mysql.go
  tests/update_bit1/drainer.toml
  tests/update_bit1/run.sh
Labels: priority/normal, status/LGT2, type/bug-fix

#657 [release-2.1] drainer: fix failure to update BIT columns with downstream TiDB (#655)
  drainer/translator/mysql.go
  tests/update_bit1/drainer.toml
  tests/update_bit1/run.sh
Labels: priority/normal, status/LGT2, type/cherry-pick

#658 [release-2.1] pump/: Fix get L0 files num and trigger vlog.gcTS step by step (#648)
  go.mod
  go.sum
  pump/server.go
  pump/storage/storage.go
  pump/storage/vlog.go
Labels: status/LGT2, type/cherry-pick, type/enhancement

#659 [release-2.1] pump: Add support to stop write at a limit avaliable space (#647)
  cmd/pump/pump.toml
  go.mod
  pump/server.go
  pump/storage/errors.go
  pump/storage/storage.go
  pump/storage/util.go
  pump/storage/util_test.go
  pump/storage/vlog.go
Labels: status/LGT2, type/cherry-pick

#662 [release2.1] reparo: add unit test && add safe mode
  go.mod
  go.sum
  reparo/config.go
  reparo/reparo.go
  reparo/syncer/memory_test.go
  reparo/syncer/mysql.go
  reparo/syncer/mysql_test.go
  reparo/syncer/print.go
  reparo/syncer/print_test.go
  reparo/syncer/syncer.go
  reparo/syncer/syncer_test.go
  reparo/syncer/translate_test.go
  reparo/syncer/util.go
  reparo/syncer/util_test.go
Labels: status/LGT2, type/cherry-pick

#660 *: Preallocate space for slices and strings
  drainer/translator/pb.go
  pkg/dml/dml.go
  pkg/loader/executor.go
  pkg/loader/model.go
Labels: status/LGT2

#661 pump: Add more tests for pump/storage
  pump/storage/storage_test.go
  pump/storage/vlog.go
  pump/storage/vlog_test.go
Labels: status/LGT2, type/test

#633 Introduce slow mode to send leveldb write requests asynchronously
  pump/storage/chaser.go
  pump/storage/chaser_test.go
  pump/storage/metrics.go
  pump/storage/storage.go
  pump/storage/storage_test.go
Labels: priority/important, status/LGT2, type/enhancement

#669 Reparo: add safe-mode in reapro example config file
  cmd/reparo/reparo.toml
Labels: status/LGT2

#666 pump: Make the pump/storage unit tests faster
  pump/storage/bench_test.go
  pump/storage/storage_test.go
  pump/storage/vlog_test.go
Labels: status/LGT2

#673 update parser dep
  arbiter/metrics.go
  drainer/checkpoint/mysql.go
  drainer/collector.go
  drainer/metrics.go
  drainer/schema.go
  drainer/schema_test.go
  drainer/server.go
  drainer/translator/flash.go
  drainer/translator/flash_test.go
  drainer/translator/flash_util.go
  drainer/translator/kafka.go
  drainer/translator/mysql.go
  drainer/translator/mysql_test.go
  drainer/translator/pb_test.go
  drainer/translator/testing.go
  go.mod
  go.sum
  pkg/sql/sql.go
  pkg/sql/sql_test.go
  pkg/util/p8s.go
  pkg/util/util_test.go
  pump/metrics.go
  pump/server.go
  reparo/syncer/translate_test.go
  reparo/syncer/util.go
  reparo/syncer/util_test.go
  tests/dailytest/db.go
  tests/dailytest/job.go
Labels: status/LGT2, status/PTAL

#674 handle Recover job and fix can't close internally
  drainer/schema.go
  drainer/server.go
Labels: status/LGT2

#591 tests: Add integration test case for view creation
  tests/dailytest/case.go
Labels: status/LGT2

#667 drainer: fix failure to update BIT columns with downstream TiDB when message passes through Kafka
  arbiter/server.go
  arbiter/server_test.go
  pkg/loader/translate.go
  pkg/loader/translate_test.go
  tests/dailytest/case.go
  tests/kafka/kafka.go
  tests/update_bit1/drainer.toml
  tests/update_bit1/run.sh
Labels: status/LGT1

#663 refine gc strategy of pump (#646)
  pump/config.go
  pump/metrics.go
  pump/server.go
  pump/storage/storage.go
Labels: status/LGT2, type/cherry-pick

#670 drainer: fix ts map
  drainer/checkpoint/checkpoint.go
  drainer/checkpoint/flash.go
  drainer/checkpoint/flash_test.go
  drainer/checkpoint/kafka.go
  drainer/checkpoint/kafka_test.go
  drainer/checkpoint/mysql.go
  drainer/checkpoint/mysql_test.go
  drainer/checkpoint/pb.go
  drainer/checkpoint/pb_test.go
  drainer/sync/mysql.go
  drainer/sync/syncer.go
  drainer/sync/syncer_test.go
  drainer/syncer.go
  pkg/loader/load.go
  pkg/loader/load_test.go
  pkg/loader/model.go
Labels: priority/normal, status/LGT3, type/bug-fix

#678 tests: No need to wait for seconds before closing
  pump/storage/storage.go
  pump/storage/storage_test.go
Labels: status/LGT1, type/test

#668 drainer: Refactor translator/kafka.go to make it simpler
  drainer/translator/kafka.go
Labels: status/LGT1

#683 pkg/sql: add missing error code of IgnoreDDLError
  pkg/sql/sql.go
  pkg/sql/sql_test.go
Labels: status/LGT1

#682 Add recover test and change downstream TiDB storage to TiKV
  tests/dailytest/case.go
  tests/run.sh
Labels: status/LGT1

#681 pump/: Refine log when no available space
  pump/storage/errors.go
  pump/storage/storage.go
Labels: needs-cherry-pick-2.1, status/LGT2, type/enhancement

#677 Split composite DDL like "use <db>; <ddl>;" to improve DDL compatibility
  drainer/executor/mysql.go
  drainer/syncer.go
  drainer/translator/mysql.go
  drainer/translator/translator_test.go
Labels: status/LGT2

#685 drainer/: Add ignore-txn-commit-ts to skip some txn
  cmd/drainer/drainer.toml
  drainer/config.go
  drainer/syncer.go
  drainer/syncer_test.go
Labels: needs-cherry-pick-2.1, status/LGT2

#686 pkg/sql: add missing error code of IgnoreDDLError
  pkg/sql/sql.go
Labels: status/LGT2, status/PTAL, type/cherry-pick

#684 add node-id cmd to specify drainer's node-id
  cmd/drainer/README.md
  cmd/pump/README.md
  drainer/config.go
  drainer/server.go
  pump/config.go
Labels: status/LGT2

#687 Return error when loading some undefined configs from local
  arbiter/config.go
  arbiter/config_test.go
  drainer/config.go
  drainer/config_test.go
  pkg/util/util.go
  pump/config.go
  pump/config_test.go
  reparo/config.go
  reparo/config_test.go
Labels: status/LGT2, status/PTAL

#688 server.go: refine log when not in online state
  pump/server.go
Labels: needs-cherry-pick-2.1, status/LGT2

#689 update package github.com/Shopify/sarama from v1.18.0 to v1.23.1, git…
  go.mod
  go.sum
Labels: needs-cherry-pick-2.1, status/LGT2

#694 update versions of sarama & mysql driver dependencies for binlogv2.1
  go.mod
  go.sum
Labels: status/LGT2, status/PTAL

#693 server.go: refine log when not in online state
  go.mod
  pump/server.go
  pump/storage/storage.go
Labels: status/LGT2, type/cherry-pick

#695 binlogctl: Use registry.Node to get a single node directly
  binlogctl/nodes.go
  binlogctl/nodes_test.go
Labels: status/LGT2
