Repository pingcap/tidb-binlog, pull requests merged in 2020-01, with the labels that each got.

#862 Add unique key info in slave proto (#858)
  drainer/translator/kafka.go
  drainer/translator/kafka_test.go
  go.mod
  go.sum
Labels: status/LGT2, status/can merge, type/cherry-pick

#863 Avoid the sleep style for doing nothing
  drainer/syncer.go
Labels: priority/important, status/LGT2, status/PTAL

#865 drainer: Clear the cache instead of refreshing after DDL to avoid unnecessary queries
  pkg/loader/load.go
Labels: status/LGT1

#857 Add encrypt password config support
  binlogctl/config.go
  binlogctl/encrypt.go
  cmd/binlogctl/main.go
  cmd/drainer/drainer.toml
  drainer/config.go
  drainer/config_test.go
  drainer/sync/util.go
  pkg/encrypt/encrypt.go
  pkg/encrypt/encrypt_test.go
  scripts/groovy/binlog_ghpr_integration.groovy
Labels: needs-cherry-pick-3.0, status/LGT2, status/PTAL

#868 Add encrypt password config support (#857)
  binlogctl/config.go
  binlogctl/encrypt.go
  cmd/binlogctl/main.go
  cmd/drainer/drainer.toml
  drainer/config.go
  drainer/config_test.go
  drainer/sync/util.go
  pkg/encrypt/encrypt.go
  pkg/encrypt/encrypt_test.go
Labels: status/LGT2, status/PTAL, type/cherry-pick

#871 metrics: add grafana and alertmanager scripts
  metrics/alertmanager/binlog.rules.yml
  metrics/grafana/binlog.json
Labels: priority/normal, status/LGT2

#872 metrics: add grafana and alertmanager scripts
  metrics/alertmanager/binlog.rules.yml
  metrics/grafana/binlog.json
Labels: priority/normal, status/PTAL

#870 metrics: add grafana and alertmanager scripts
  metrics/alertmanager/binlog.rules.yml
  metrics/grafana/binlog.json
Labels: priority/normal, status/LGT2

#867 Add sync mode config to allow mismatch column number
  cmd/drainer/drainer.toml
  drainer/sync/mysql.go
  drainer/sync/mysql_test.go
  drainer/sync/util.go
  pkg/loader/load.go
  pkg/loader/load_test.go
Labels: status/LGT2, status/PTAL

#879 binlog loop back sync
  cmd/drainer/drainer.toml
  drainer/config.go
  drainer/loopbacksync/loopbacksync.go
  drainer/loopbacksync/loopbacksync_test.go
  drainer/sync/mysql.go
  drainer/sync/syncer_test.go
  drainer/syncer.go
  drainer/syncer_test.go
  pkg/loader/executor.go
  pkg/loader/load.go
  pkg/loader/load_test.go
  pkg/loader/model.go
  pkg/loader/model_test.go
Labels: contribution, status/LGT2

#884 binlog loop back sync
  cmd/drainer/drainer.toml
  drainer/config.go
  drainer/loopbacksync/loopbacksync.go
  drainer/loopbacksync/loopbacksync_test.go
  drainer/sync/mysql.go
  drainer/sync/mysql_test.go
  drainer/sync/syncer_test.go
  drainer/sync/util.go
  drainer/syncer.go
  drainer/syncer_test.go
  pkg/loader/executor.go
  pkg/loader/load.go
  pkg/loader/load_test.go
  pkg/loader/model.go
  pkg/loader/model_test.go
Labels: status/LGT2, type/cherry-pick
