Repository pingcap/tidb-binlog, pull requests merged in 2020-04, with the labels that each got.

#941 Skip the tiflash job.
  drainer/schema.go
  drainer/syncer.go
  pkg/loader/load.go
  pkg/loader/load_test.go
  tests/run.sh
Labels: needs-cherry-pick-3.1

#947 skip wrongly write ActionUpdateTiFlashReplicaStatus job
  drainer/schema.go
  tests/filter/run.sh
Labels: needs-cherry-pick-3.1

#949 Refine log when enable tls
  drainer/config.go
  drainer/server.go
  pump/config.go
  pump/server.go
Labels: needs-cherry-pick-3.1, status/LGT1

#952 Update parser&tidb to latest version of 4.0
  go.mod
  go.sum
Labels: status/PTAL

#956 modify Drainer 's Syncer interface
  drainer/sync/kafka.go
  drainer/sync/mysql.go
  drainer/sync/pb.go
  drainer/sync/syncer.go
  drainer/syncer.go
Labels: contribution, status/LGT1, status/can-merge

#957 modify syncer interface (#956)
  drainer/sync/kafka.go
  drainer/sync/mysql.go
  drainer/sync/pb.go
  drainer/sync/syncer.go
  drainer/syncer.go
Labels: status/PTAL, type/cherry-pick

#950 Handle create/drop sequence job type
  drainer/collector.go
  drainer/schema.go
  tests/sequence/drainer.toml
  tests/sequence/run.sh
Labels: status/LGT2, status/can-merge
