Repository pingcap/tidb-binlog, pull requests merged in 2020-12, with the labels that each got.

#1020 update dependency for release-3.0
  binlogctl/meta_test.go
  go.mod
  go.sum
  pkg/security/security_test.go
  pkg/util/util_test.go
  pump/server_test.go
Labels: first-time-contributor, status/LGT1, status/can-merge

#1025 pump: check txn TTL before check IsCommitted
  go.mod
  go.sum
  pump/storage/storage.go
Labels: status/LGT1

#1002 mod: update tidb dependency to latest && fix incompatible problem
  drainer/collector_test.go
  drainer/translator/kafka.go
  drainer/translator/mysql.go
  drainer/translator/pb.go
  drainer/translator/translator.go
  drainer/util.go
  go.mod
  go.sum
  pkg/util/signal_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  reparo/ddl.go
  reparo/syncer/translate.go
  reparo/syncer/util.go
  tests/dailytest/db.go
  tests/gencol/run.sh
Labels: status/LGT2
