Repository pingcap/tidb-binlog, pull requests merged in 2020-06, with the labels that each got.

#975 Enable allow_auto_random_explicit_insert if it's suppported
  pkg/loader/util.go
  tests/dailytest/case.go
  tests/kafka/kafka.go
Labels: needs-cherry-pick-3.1, status/LGT2

#976 Enable allow_auto_random_explicit_insert if it's suppported
  pkg/loader/util.go
  tests/dailytest/case.go
  tests/kafka/kafka.go
Labels: status/LGT2, type/cherry-pick

#982 update black/white list and some description about master/slave
  arbiter/server.go
  drainer/checkpoint/checkpoint.go
  drainer/checkpoint/file.go
  drainer/checkpoint/mysql.go
  drainer/checkpoint/mysql_test.go
  drainer/relay.go
  drainer/relay/reader.go
  drainer/relay/reader_test.go
  drainer/relay/relayer.go
  drainer/sync/kafka.go
  drainer/syncer.go
  drainer/translator/kafka.go
  drainer/translator/kafka_test.go
  pkg/filter/filter.go
  pkg/loader/README.md
  pkg/loader/load.go
  pkg/loader/translate.go
  pkg/loader/translate_test.go
  pkg/sql/sql.go
  tests/kafka/kafka.go
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/PTAL
