Repository pingcap/tidb-binlog, pull requests merged in 2020-03, with the labels that each got.

#918 Make the column order deterministic
  pkg/loader/model.go
Labels: status/PTAL, type/test

#920 Update parser add test for auto_random
  go.mod
  go.sum
  tests/dailytest/case.go
  tests/run.sh
Labels: status/LGT2

#915 compatible with the old version and take effect of dispatch and causality
  cmd/drainer/drainer.toml
  drainer/config.go
  drainer/config_test.go
  drainer/relay.go
  drainer/sync/mysql.go
  drainer/sync/syncer_test.go
  drainer/syncer.go
  pkg/loader/load.go
  pkg/loader/load_test.go
  tests/binlog/drainer.toml
Labels: needs-cherry-pick-3.0, status/LGT2

#921 Update parser/tidb add test for auto_random
  binlogctl/meta_test.go
  drainer/translator/testing.go
  go.mod
  go.sum
  pkg/util/util_test.go
  pump/server_test.go
  tests/dailytest/case.go
  tests/run.sh
Labels: status/LGT2

#929 drainer: add KafkaClientID in DBConfig (#902)
  cmd/drainer/drainer.toml
  drainer/sync/kafka.go
  drainer/sync/util.go
  tests/binlog/drainer.toml
Labels: status/LGT1, type/cherry-pick

#927 Reload cert/key for every new conn
  go.sum
  pkg/security/security.go
  pkg/security/security_test.go
Labels: status/LGT2

#926 Reload cert/key of tls for new connection in pd/kv client
  binlogctl/meta.go
  binlogctl/meta_test.go
  drainer/server_test.go
  drainer/translator/testing.go
  go.mod
  go.sum
  pkg/security/security_test.go
  pkg/util/ts.go
  pkg/util/ts_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  pump/server.go
  pump/server_test.go
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/LGT2

#931 support TLS for components and downstream db
  arbiter/server.go
  arbiter/server_test.go
  binlogctl/config.go
  binlogctl/nodes.go
  binlogctl/nodes_test.go
  cmd/binlogctl/main.go
  cmd/drainer/drainer.toml
  cmd/pump/main.go
  drainer/collector.go
  drainer/config.go
  drainer/pump.go
  drainer/pump_test.go
  drainer/relay.go
  drainer/server.go
  drainer/sync/mysql.go
  drainer/sync/syncer_test.go
  drainer/sync/util.go
  pkg/loader/example_loader_test.go
  pkg/loader/util.go
  pkg/security/security.go
  pkg/security/security_test.go
  pkg/util/net.go
  pkg/util/net_test.go
  pump/config.go
  pump/server.go
  pump/server_test.go
  reparo/syncer/mysql.go
  reparo/syncer/mysql_test.go
  tests/_utils/check_status
  tests/_utils/run_drainer
  tests/_utils/run_pump
  tests/restart/run.sh
  tests/run.sh
  tests/status/drainer.toml
  tests/status/run.sh
Labels: status/LGT1

#934 support common name check for tls
  cmd/drainer/drainer.toml
  cmd/pump/pump.toml
  pkg/security/security.go
  tests/_utils/run_drainer
  tests/_utils/run_pump
  tests/run.sh
Labels: status/LGT2, type/feature

#937 support common name check for tls(#934)
  cmd/drainer/drainer.toml
  cmd/pump/pump.toml
  pkg/security/security.go
  tests/_utils/run_drainer
  tests/_utils/run_pump
  tests/run.sh
Labels: needs-cherry-pick-3.1, status/LGT2, type/cherry-pick

#939 Reload cert/key of tls for new connection in pd/kv client
  binlogctl/meta.go
  binlogctl/meta_test.go
  drainer/server_test.go
  go.mod
  go.sum
  pkg/security/security_test.go
  pkg/util/ts.go
  pkg/util/ts_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  pump/server.go
  pump/server_test.go
Labels: status/LGT2, type/cherry-pick
