Repository pingcap/tidb-binlog, pull requests merged in 2020-05, with the labels that each got.

#960 .*: update max message size for grpc
  drainer/config.go
  drainer/config_test.go
  drainer/util.go
  pump/config.go
  pump/server.go
Labels: status/LGT2

#962 Fix unknown type for mediumint
  drainer/translator/kafka.go
Labels: needs-cherry-pick-3.0, status/LGT2, status/can-merge

#961 Fix not quote db name in file data ddl
  drainer/translator/pb.go
  drainer/translator/pb_test.go
  tests/reparo/config.toml
  tests/reparo/run.sh
  tests/reparo/sync_diff_inspector.toml
Labels: needs-cherry-pick-3.0, status/LGT2, status/can-merge

#965 test: add test cases for range/hash partition
  tests/partition/drainer.toml
  tests/partition/run.sh
Labels: status/LGT2, type/test

#971 Fix notify drainer not enable tls
  pump/node.go
  tests/dailytest/case.go
Labels: needs-cherry-pick-3.0, status/LGT1

#972 Fix notify drainer not enable tls
  pump/node.go
Labels: type/cherry-pick

#958 Fix multi rows of same table split into multi table in the downstream format
  drainer/translator/kafka.go
  drainer/translator/kafka_test.go
  drainer/translator/testing.go
Labels: needs-cherry-pick-3.0, status/LGT1, status/can-merge
