Repository pingcap/tidb-binlog, pull requests merged in 2020-02, with the labels that each got.

#885 drainer: Fix #724, Enable drainer to purge old incremental backup data on disk
  cmd/drainer/drainer.toml
  drainer/relay/relayer.go
  drainer/sync/pb.go
  drainer/sync/syncer_test.go
  drainer/sync/util.go
  drainer/syncer.go
  pkg/binlogfile/binlogger.go
  pkg/binlogfile/binlogger_test.go
Labels: need-update-docs, needs-cherry-pick-3.0, status/LGT2

#890 Fix current DML&DDL corner case for bidirectional replication
  drainer/sync/mysql.go
  drainer/sync/syncer.go
  drainer/syncer.go
  drainer/translator/mysql.go
  drainer/translator/mysql_test.go
  pkg/loader/executor.go
  pkg/loader/executor_test.go
  pkg/loader/load.go
  pkg/loader/load_test.go
  pkg/loader/model.go
  pkg/loader/model_test.go
  reparo/syncer/mysql_test.go
  reparo/syncer/print_test.go
  reparo/syncer/translate_test.go
Labels: status/LGT2

#883 feed downstream by relay log at startup if need
  cmd/drainer/drainer.toml
  drainer/checkpoint/checkpoint.go
  drainer/checkpoint/file.go
  drainer/checkpoint/file_test.go
  drainer/checkpoint/mysql.go
  drainer/checkpoint/mysql_test.go
  drainer/checkpoint/util.go
  drainer/checkpoint/util_test.go
  drainer/config.go
  drainer/relay.go
  drainer/relay/reader.go
  drainer/relay/reader_test.go
  drainer/relay/relayer.go
  drainer/relay_test.go
  drainer/server.go
  drainer/sync/mysql.go
  drainer/sync/syncer.go
  drainer/syncer.go
  drainer/syncer_test.go
  pkg/util/util.go
Labels: need-update-docs, status/LGT2

#892 Fix current DML&DDL corner case for bidirectional replication (#890)
  drainer/checkpoint/file_test.go
  drainer/relay_test.go
  drainer/sync/mysql.go
  drainer/sync/syncer.go
  drainer/syncer.go
  drainer/translator/mysql.go
  drainer/translator/mysql_test.go
  pkg/loader/executor.go
  pkg/loader/executor_test.go
  pkg/loader/load.go
  pkg/loader/load_test.go
  pkg/loader/model.go
  pkg/loader/model_test.go
  reparo/syncer/mysql_test.go
  reparo/syncer/print_test.go
  reparo/syncer/translate_test.go
Labels: status/PTAL

#893 support relay log
  cmd/drainer/drainer.toml
  drainer/checkpoint/checkpoint.go
  drainer/checkpoint/file.go
  drainer/checkpoint/file_test.go
  drainer/checkpoint/flash.go
  drainer/checkpoint/flash_test.go
  drainer/checkpoint/mysql.go
  drainer/checkpoint/mysql_test.go
  drainer/checkpoint/util.go
  drainer/checkpoint/util_test.go
  drainer/config.go
  drainer/relay.go
  drainer/relay/reader.go
  drainer/relay/reader_test.go
  drainer/relay/relayer.go
  drainer/relay/relayer_test.go
  drainer/relay_test.go
  drainer/server.go
  drainer/sync/flash_test.go
  drainer/sync/mysql.go
  drainer/sync/mysql_test.go
  drainer/sync/pb.go
  drainer/sync/syncer.go
  drainer/sync/syncer_test.go
  drainer/syncer.go
  drainer/syncer_test.go
  drainer/translator/kafka_test.go
  drainer/translator/mysql_test.go
  drainer/translator/pb_test.go
  drainer/translator/testing.go
  pkg/binlogfile/binlogger.go
  pkg/binlogfile/binlogger_test.go
  pkg/loader/model.go
  pkg/util/util.go
  reparo/file_test.go
Labels: status/LGT2

#894 Support TLS to connect mysql/TiDB
  arbiter/server.go
  arbiter/server_test.go
  cmd/drainer/drainer.toml
  drainer/config.go
  drainer/relay.go
  drainer/sync/mysql.go
  drainer/sync/syncer_test.go
  drainer/sync/util.go
  pkg/loader/example_loader_test.go
  pkg/loader/util.go
  reparo/syncer/mysql.go
  reparo/syncer/mysql_test.go
Labels: status/LGT1

#895 Rename Status as Consistent
  drainer/checkpoint/checkpoint.go
  drainer/checkpoint/file.go
  drainer/checkpoint/file_test.go
  drainer/checkpoint/mysql.go
  drainer/checkpoint/mysql_test.go
  drainer/relay.go
  drainer/relay_test.go
  drainer/syncer.go
Labels: needs-cherry-pick-3.0, status/LGT2

#897 drainer: remove deprecated syncer flash (#812)
  cmd/drainer/drainer.toml
  drainer/checkpoint/checkpoint.go
  drainer/checkpoint/flash.go
  drainer/checkpoint/flash_test.go
  drainer/sync/flash.go
  drainer/sync/flash_test.go
  drainer/sync/syncer_test.go
  drainer/sync/util.go
  drainer/syncer.go
  drainer/translator/flash.go
  drainer/translator/flash_util.go
  drainer/util.go
  go.mod
  go.sum
  tests/binlog/drainer.toml
  tests/filter/drainer.toml
  tests/flash/config.toml
  tests/flash/flash.go
  tests/kafka/drainer.toml
  tests/reparo/drainer.toml
  tests/restart/drainer.toml
  tests/status/drainer.toml
Labels: status/LGT1

#899 upgrade grpc to 1.23
  drainer/server.go
  go.mod
  go.sum
  pump/node.go
  pump/server.go
Labels: priority/important, status/LGT2

#902 drainer: add KafkaClientID in DBConfig
  cmd/drainer/drainer.toml
  drainer/sync/kafka.go
  drainer/sync/util.go
  tests/binlog/drainer.toml
Labels: contribution

#904 support TLS for components
  binlogctl/config.go
  binlogctl/nodes.go
  binlogctl/nodes_test.go
  cmd/binlogctl/main.go
  cmd/pump/main.go
  drainer/collector.go
  drainer/pump.go
  drainer/pump_test.go
  drainer/server.go
  pkg/security/security.go
  pkg/util/net.go
  pkg/util/net_test.go
  pump/config.go
  pump/server.go
  pump/server_test.go
  tests/_utils/check_status
  tests/_utils/run_drainer
  tests/_utils/run_pump
  tests/restart/run.sh
  tests/run.sh
  tests/status/drainer.toml
  tests/status/run.sh
Labels: need-update-ansible, needs-cherry-pick-3.0, status/LGT2

#903 Optimize the performance of bidirectional synchronous update table of _drainer_repl_mark
  drainer/loopbacksync/loopbacksync.go
  pkg/loader/executor.go
  pkg/loader/load.go
  pkg/loader/model.go
  pkg/loader/model_test.go
Labels: contribution, needs-cherry-pick-3.0, status/LGT2, status/can merge

#912 fix initMarkTable failed case not quit normally and refactor
  drainer/loopbacksync/loopbacksync.go
  drainer/loopbacksync/loopbacksync_test.go
  pkg/loader/executor.go
  pkg/loader/load.go
  pkg/loader/model.go
  pkg/loader/model_test.go
Labels: needs-cherry-pick-3.0, status/LGT2, status/can merge
