Repository pingcap/tidb-binlog, pull requests merged in 2021-12, with the labels that each got.

#1089 Fix the issue #1088 Reparo: Add a support CreateView function
  reparo/ddl.go
  reparo/syncer/translate.go
  reparo/syncer/translate_test.go
Labels: status/LGT2, status/can-merge, contribution, first-time-contributor, size/S

#1094 replicate dml statements in binlog to oracle
  Makefile
  drainer/sync/mysql.go
  drainer/sync/oracle.go
  drainer/sync/oracle_test.go
  drainer/sync/util.go
  drainer/syncer.go
  drainer/translator/mysql.go
  drainer/translator/oracle.go
  drainer/translator/oracle_test.go
  drainer/util.go
  go.mod
  go.sum
  pkg/loader/executor.go
  pkg/loader/executor_test.go
  pkg/loader/load.go
  pkg/loader/load_test.go
  pkg/loader/model.go
  pkg/loader/model_test.go
  pkg/loader/util.go
  pkg/loader/util_test.go
Labels: status/LGT2, status/can-merge, first-time-contributor, size/XXL

#1095 replicate ddl data in binlog to oracle
  Makefile
  drainer/syncer.go
  drainer/util.go
  pkg/loader/load.go
  pkg/loader/load_test.go
Labels: status/LGT2, status/can-merge, size/L

#1100 tests: update sync-diff conf
  tests/_utils/check_data
  tests/reparo/run.sh
  tests/reparo/sync_diff_inspector.toml
  tests/restart/sync_diff_inspector.toml
Labels: type/test, status/LGT2, status/can-merge, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, cherry-pick-approved, size/L

#1103 reparo: fix can't decode bit type data
  reparo/syncer/util.go
  reparo/syncer/util_test.go
  tests/dailytest/db.go
  tests/reparo/binlog.go
Labels: status/LGT2, status/can-merge, first-time-contributor, size/S

#1099 add issue requirement to pull request template
  .github/pull_request_template.md
Labels: status/LGT2, status/can-merge, size/S

#1097 adaptation to oracle checkpoint
  drainer/checkpoint/checkpoint.go
  drainer/checkpoint/mysql_test.go
  drainer/checkpoint/oracle.go
  drainer/checkpoint/oracle_test.go
  drainer/checkpoint/util.go
  drainer/sync/mysql.go
  drainer/sync/util.go
  drainer/util.go
  drainer/util_test.go
  pkg/loader/load.go
  pkg/sql/sql.go
  pkg/sql/sql_test.go
Labels: status/LGT2, status/can-merge, size/XXL

#1104 relay log for oracle
  arbiter/server.go
  drainer/relay.go
  drainer/relay/reader_test.go
  drainer/relay_test.go
  drainer/translator/kafka.go
  go.mod
  go.sum
  pkg/loader/translate.go
  pkg/loader/translate_test.go
  tests/kafka/kafka.go
Labels: status/LGT2, status/can-merge, size/XL

#1115 drainer: skip 'alter table cache|nocache' DDL jobs
  drainer/schema.go
  tests/cache_table/drainer.toml
  tests/cache_table/run.sh
Labels: status/LGT2, status/can-merge, size/M
