Repository pingcap/tidb-binlog, pull requests merged in 2021-11, with the labels that each got.

#1083 drainer: skip alter attributes DDL
  Makefile
  arbiter/server.go
  drainer/binlog_item.go
  drainer/collector.go
  drainer/collector_test.go
  drainer/config.go
  drainer/config_test.go
  drainer/pump.go
  drainer/schema.go
  drainer/schema_test.go
  drainer/server.go
  drainer/syncer.go
  drainer/syncer_test.go
  drainer/translator/kafka.go
  drainer/translator/kafka_test.go
  drainer/translator/mysql.go
  drainer/translator/mysql_test.go
  drainer/translator/pb.go
  drainer/translator/pb_test.go
  drainer/translator/table_info.go
  drainer/translator/testing.go
  drainer/translator/translator.go
  drainer/util.go
  go.mod
  go.sum
  pkg/loader/load.go
  pkg/security/security.go
  pkg/sql/sql.go
  pkg/util/ts.go
  pkg/util/util.go
  pkg/util/util_test.go
  pump/server.go
  pump/server_test.go
  pump/storage/helper.go
  pump/storage/storage.go
  pump/storage/storage_test.go
  reparo/config.go
  reparo/ddl.go
  reparo/file_test.go
  reparo/reparo.go
  reparo/syncer/translate.go
  reparo/syncer/translate_test.go
  reparo/syncer/util.go
  reparo/syncer/util_test.go
  tests/attributes/drainer.toml
  tests/dailytest/db.go
  tests/dailytest/job.go
  tests/dailytest/parser.go
Labels: status/LGT2, status/can-merge, size/XXL

#1084 Update tidb-tools dependency
  go.mod
  go.sum
  tests/_utils/check_data
  tests/reparo/run.sh
  tests/reparo/sync_diff_inspector.toml
  tests/restart/sync_diff_inspector.toml
Labels: status/LGT2, status/can-merge, size/L

#1085 proto: update proto name and remove conflictPolicy
  Makefile
  proto/binlog/binlog.pb.go
  proto/pb_binlog.proto
Labels: status/LGT2, status/can-merge, size/XL

#1090 loader: clear txns and dmls buffer to free memory
  pkg/loader/load.go
Labels: status/LGT2, status/can-merge, first-time-contributor, size/XS

#1092 dependencies: update tidb dependencies
  go.mod
  go.sum
  tests/_utils/check_data
  tests/reparo/run.sh
  tests/reparo/sync_diff_inspector.toml
  tests/restart/sync_diff_inspector.toml
Labels: status/LGT2, status/can-merge, cherry-pick-approved, size/L

#1086 syncer: add table router and binlog event filters in drainer
  drainer/config.go
  drainer/sync/mysql.go
  drainer/syncer.go
  drainer/syncer_test.go
  drainer/util.go
  drainer/util_test.go
  pkg/loader/load.go
  pkg/loader/util.go
  reparo/syncer/translate.go
  tests/binlogfilter/drainer.toml
  tests/binlogfilter/run.sh
Labels: status/LGT2, status/can-merge, size/XXL
