Repository pingcap/tidb-binlog, pull requests merged in 2021-05, with the labels that each got.

#1040 drainer: support replica clustered index table
  drainer/collector.go
  drainer/server.go
  drainer/translator/kafka.go
  drainer/translator/mysql.go
  drainer/translator/pb.go
  drainer/translator/translator.go
  go.mod
  go.sum
  pkg/security/security.go
  pkg/security/security_test.go
  pump/server.go
  pump/server_test.go
  tests/dailytest/case.go
  tests/run.sh
Labels: status/LGT2, status/PTAL

#1044 cmd: update drainer configuration's comments
  cmd/drainer/drainer.toml
  cmd/pump/pump.toml
Labels: needs-cherry-pick-5.0, status/PTAL

#1047 drainer: fix collation clustered pk as wrong value
  drainer/translator/translator.go
  tests/dailytest/case.go
Labels: status/PTAL, type/bug-fix
