Repository pingcap/tidb-binlog, pull requests merged in 2022-07, with the labels that each got.

#1174 ddl: change interface
  drainer/sync/mysql.go
  drainer/translator/testing.go
  drainer/util.go
  go.mod
  go.sum
  reparo/ddl.go
  reparo/syncer/translate.go
Labels: status/LGT2, status/can-merge, size/L

#1173 drainer: load infos from dump files
  drainer/collector.go
  drainer/config.go
  drainer/schema.go
  drainer/schema_test.go
  drainer/server.go
  drainer/syncer.go
  drainer/syncer_test.go
  drainer/util.go
  drainer/util_test.go
  go.mod
  go.sum
Labels: status/LGT1, do-not-merge/cherry-pick-not-approved, size/XXL, do-not-merge/needs-linked-issue

#1176 fix version
  drainer/syncer.go
Labels: status/LGT1, size/XS, do-not-merge/cherry-pick-not-approved

#1172 Add test for DDL "set tiflash mode"
  go.mod
  go.sum
  pkg/loader/load.go
  pkg/loader/load_test.go
Labels: status/LGT2, status/can-merge, first-time-contributor, size/M

#1178 drainer: load table infos from kvstorge
  drainer/config.go
  drainer/schema.go
  drainer/schema_test.go
  drainer/server.go
  drainer/util.go
Labels: status/LGT1, size/M, do-not-merge/cherry-pick-not-approved

#1180 drainer: support concurrent DDL
  drainer/schema.go
  drainer/syncer.go
Labels: status/LGT2, status/can-merge, size/S

#1182 reparo: support pprof and metrics
  reparo/config.go
  reparo/decode.go
  reparo/http_handler.go
  reparo/metrics.go
  reparo/reparo.go
  reparo/syncer/mysql.go
  reparo/syncer/mysql_test.go
  reparo/syncer/syncer.go
  reparo/syncer/syncer_test.go
Labels: status/LGT1, cherry-pick-approved, size/L

#1183 fix prometheus.registry
  reparo/metrics.go
Labels: status/LGT1, size/XS, do-not-merge/cherry-pick-not-approved
