Repository pingcap/tidb-binlog, pull requests merged in 2022-05, with the labels that each got.

#1158 drainer:sync lob data to oracle
  drainer/translator/mysql.go
  drainer/translator/oracle.go
  drainer/translator/pb.go
  go.mod
  go.sum
  pkg/loader/executor.go
  pkg/loader/executor_test.go
  pkg/loader/load.go
  pkg/loader/load_test.go
  pkg/loader/model.go
  pkg/loader/model_test.go
  pkg/loader/util.go
Labels: status/LGT2, status/can-merge, size/XXL

#1160 drainer/translater: fix the bug that drainer writes incorrect time data
  drainer/pump.go
  drainer/sync/kafka.go
  drainer/sync/mysql.go
  drainer/sync/mysql_test.go
  drainer/sync/oracle.go
  drainer/sync/oracle_test.go
  drainer/sync/pb.go
  drainer/sync/syncer.go
  drainer/sync/syncer_test.go
  drainer/syncer.go
  drainer/translator/kafka.go
  drainer/translator/mysql.go
  drainer/translator/mysql_test.go
  drainer/translator/oracle.go
  drainer/translator/pb.go
  drainer/translator/translator.go
  pump/server.go
  pump/server_test.go
  pump/storage/storage.go
  pump/storage/storage_test.go
  tests/binlog/run.sh
  tests/dailytest/case.go
Labels: status/LGT2, status/can-merge, size/XL

#1165 drainer: rtrim char type column in sql
  pkg/loader/model.go
  pkg/loader/model_test.go
  pkg/loader/util.go
  pkg/loader/util_test.go
Labels: status/LGT2, status/can-merge, size/L
