Repository pingcap/tidb-binlog, pull requests merged in 2022-03, with the labels that each got.

#1114 drainer: make drainer compatiable with batch create tables job
  drainer/schema.go
  drainer/syncer.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/M, needs-cherry-pick-5.4

#1141 drainer: Ignore all tidb placement operations
  pkg/loader/util.go
  tests/placement_rules/run.sh
Labels: status/LGT2, status/can-merge, first-time-contributor, size/S

#1142 update to go1.18
  Makefile
  drainer/pump_test.go
  drainer/util.go
  go.mod
  pkg/loader/bench_test.go
  pkg/security/security_test.go
  pump/storage/log_default.go
  pump/storage/log_linux.go
  reparo/reparo_test.go
  tests/dailytest/parser.go
  tools/check/go.mod
  tools/check/go.sum
Labels: status/LGT2, status/can-merge, size/XXL

#1146 dependency: update binlog parser/tidb/etcd to release-6.0
  arbiter/metrics.go
  binlogctl/nodes_test.go
  drainer/checkpoint/file.go
  drainer/config_test.go
  drainer/metrics.go
  drainer/pump.go
  drainer/server_test.go
  go.mod
  go.sum
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/node/registry_test.go
  pkg/sql/sql.go
  pkg/util/duration.go
  pkg/util/signal_test.go
  pump/metrics.go
  pump/node.go
  pump/server_test.go
Labels: status/LGT2, status/can-merge, size/XXL

#1144 drainer: filter out placement special comments in ddl
  pkg/loader/load.go
  pkg/loader/load_test.go
  pkg/loader/util.go
  pkg/loader/util_test.go
Labels: status/LGT2, status/can-merge, size/L

#1149 sync/kafka: handle success messages in order
  drainer/sync/kafka.go
  drainer/sync/kafka_test.go
Labels: status/LGT2, status/can-merge, size/L

#1153 pump: try to fix marshal marshaling: proto: Marshal called with nil error
  drainer/server.go
  pkg/loader/load_test.go
  pump/node.go
  tests/restart/run.sh
Labels: status/LGT2, status/can-merge, cherry-pick-approved, size/S
