Repository pingcap/tidb-binlog, pull requests merged in 2022-01, with the labels that each got.

#1119 drainer: fix placement policy compatibility
  .gitignore
  drainer/collector.go
  drainer/schema.go
  tests/placement_rules/drainer.toml
  tests/placement_rules/run.sh
Labels: status/LGT2, status/can-merge, size/M, needs-cherry-pick-5.4

#1127 drainer: update dependencies to support gbk
  go.mod
  go.sum
  tests/gbk/drainer.toml
  tests/gbk/run.sh
Labels: status/LGT2, status/can-merge, cherry-pick-approved, size/L

#1130 fix sync-ddl control
  drainer/syncer.go
Labels: status/LGT2, status/can-merge, size/M

#1132 drainer: escape quote in value of column
  pkg/loader/model.go
Labels: status/LGT2, status/can-merge, size/XS
