Repository pingcap/tidb-binlog, pull requests merged in 2022-09, with the labels that each got.

#1205 drainer: fix release 0830 unit test
  Makefile
  drainer/schema.go
Labels: size/XS, cherry-pick-approved

#1206 fmt: format code with go 1.19
  drainer/binlog_item.go
  drainer/loopbacksync/loopbacksync.go
  drainer/sync/mysql_test.go
  drainer/sync/oracle_test.go
  drainer/sync/syncer_test.go
  drainer/translator/oracle_test.go
  pkg/loader/load.go
  pkg/loader/util.go
  pkg/sql/sql.go
  pump/storage/sorter.go
  pump/storage/vlog.go
Labels: status/LGT2, status/can-merge, size/S

#1209 *: update tidb dependency
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/XL
