Repository pingcap/tidb-binlog, pull requests merged in 2023-05, with the labels that each got.

#1229 skip the "cancled" ddl in ddl history
  drainer/syncer.go
  drainer/syncer_test.go
Labels: status/LGT2, status/can-merge, size/M

#1226 chore: migrate to new prow reviewing
  OWNERS
Labels: status/LGT2, status/can-merge, first-time-contributor, size/M

#1233 drainer: support load table infos to save memory and add gc safepoint update
  drainer/config.go
  drainer/safepoint.go
  drainer/schema.go
  drainer/schema_test.go
  drainer/server.go
  drainer/util.go
Labels: status/LGT2, status/can-merge, size/L
